### PR TITLE
Boilerplate: Update to 79550f8ca58f1990e817fc738962cdd37285b3ab

### PR DESCRIPTION
**Pull request by 2uasimojo**
Conventions:
- openshift/golang-osd-operator: Update
---
https://github.com/openshift/boilerplate/compare/946651c6eb6934f25ff1c80d8f99dc07eea3ff85...79550f8ca58f1990e817fc738962cdd37285b3ab

commit: 16481ab7aaf28df0c29fd82ae523d9e334cbaad6
author: Eric Fried
Add docker image build to prow config

Tweak `make prow-config` to generate a section testing the build of the
main Dockerfile.

commit: 4b2cba329ba120eb2da4faef959b3203ae774908
author: Eric Fried
Alphabetize .ci-operator.yaml

When `make prow-config` parlays .ci-operator.yaml into (the temporary
section in) the prow configuration, apparently prow's CI cares that the
fields are ordered alphabetically.

Consumers not updated with this commit can work around this by manually
reordering in their release PR.

And this will become n/a anyway once [DPTP-1640](https://issues.redhat.com/browse/DPTP-1640) is gone.

commit: 8ea9a0a330562bc591b3260885099694262f3f45
author: Eric Fried
Use https for git in tests

This avoids needing to set up ssh in prow.

commit: 26c6103e4298539a9516140231361f3252554119
author: Eric Fried
README: Multiple updates

Add a section to the README describing what to do when a second
boilerplate update is needed while a first is still in flight.

commit: 9f23df27cb771e41a4dbc4a5a59d421efe96e9f1
author: Eric Fried
Move consumer detection to release.sh

Consumer detection (discovering the github org, project, and branch name
of the consuming project) relies on git config being set up a certain
way, which it will be for a human's clone of the repository, but not
always in CI. Inclusion in common.sh was thus causing CI failures. So
move this logic to release.sh, which is only sourced by user-facing
scripts.

commit: 9905b2934b043d1c25c3254b80c45d16ed408d44
author: Eric Fried
Image: Tag image-v0.2.0

commit: ecff63deaf1be5fd1f5bc73bb234653076e4f4fb
author: Eric Fried
Image: Debug output for build.sh

`set -x` for build.sh so we can better tell what's going on during image
builds.

commit: 6ccb4c8c18d48ea8155e66f2f9a7852ed2c91b65
author: Eric Fried
Image: Make operator-sdk and opm executable

commit: a053c15883209d7a854798dc99fed1e65df420cb
author: Eric Fried
Image: Install ssh clients

These are needed by tests that clone things.

Note that the base image comes with ssh, but we're `yum autoremove`ing
to save space, and since there's no package with a dep on
openssh-clients, it's getting removed.

commit: 2feb72f50b902e9690e5d39ef772b9fbd6fe101e
author: Eric Fried
Image: Note why we're building git from source

Jira: [OSD-5600](https://issues.redhat.com/browse/OSD-5600)

commit: 7ef5b040147a5dd1c12674317f9c957a1e0daba6
author: Eric Fried
Set debug for ensure.sh

This will help debug CI failures (we've seen what may be flakes
`curl`ing golangci-lint) and shouldn't be _too_ noisy under other
circumstances.

commit: e51c6c7d2f20da91cf30d7811c357eb6b7df34a9
author: Eric Fried
golang-osd-operator: make codecov-secret-mapping

Add a `make` target, which can accept an optional `RELEASE_CLONE`
environment variable, creating a delta in openshift/release to request
the codecov secret mapping per the [SOP](https://github.com/openshift/ops-sop/blob/be43125239deb1f2bbc1ef54f010410e97ff6146/services/codecov.md#openshiftrelease-pr-1---secret-mapping)

This script shares a lot of logic with `prow-config`, so that's factored
out into libraries.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Generated PR. The only thing of significance here is the update to boilerplate build image-v0.2.0.

**Review by jharrington22 — APPROVED** [review]
/lgtm

**Pull request merged**
