### PR TITLE
Updated MD5 hashing to SHA224

### PR DESCRIPTION
**Pull request by robotmaxtron**
Updating a weak cypher identified by OSD Operator Threat Model Analysis.

### CODE REVIEW

**Review by jewzaam — CHANGES_REQUESTED** [review]
No description on why we're doing this change.
And where is pkg/utils/secrets even used?  From my read of things it can simply be removed along with tests.

**Comment by robotmaxtron** [comment]
@jewzaam I should've added it earlier and has now been updated. If you'd rather see the tests removed entirely, I can do that if that's preferred.

**Comment by jewzaam** [comment]
> @jewzaam I should've added it earlier and has now been updated. If you'd rather see the tests removed entirely, I can do that if that's preferred.

Thanks for the description update.  

But, I don't see where pkg/util/secrets is used so my question is can it simply be deleted and remove md5 dependency from the repo?

**Pull request closed without merging**
