### PR TITLE
ignore fake clusters

### PR DESCRIPTION
**Pull request by bmeng**
fixes https://issues.redhat.com/browse/OSD-6346

### CODE REVIEW

**Comment by mrbarge** [comment]
Could the `DeadMansSnitchIntegration` be an alternate way of doing this?

ie. adding a new entry to the `matchExpressions` for our existing DMSI's on Hive:
```
  clusterDeploymentSelector:
    matchExpressions:
    - key: hive.openshift.io/fake-cluster
      operator: NotIn
      values:
      - "true"
```

**Comment by bmeng** [comment]
Have tried with the DMSI, looks like it will only watch the `Labels` in ClusterDeployment, but the fake cluster indicator appears in the `Annotations`.

**Comment by jewzaam** [comment]
Sounds reasonable, will approve.  Putting on hold for the question of label so this is configuration and not code to implement.  If we decide to go with the annotation.

/approve
/hold

**Comment by bmeng** [comment]
close this one, use #102 instead

**Pull request closed without merging**
